<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SUBHASH" failures="1" tests="7" name="Test" time="0.053" errors="0" timestamp="2022-06-26T08:01:07 IST">
  <testcase classname="com.testng.coach.TestRetryanalyse" name="passWord" time="0.009">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.coach.TestRetryanalyse" name="passWord" time="0.002">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.coach.TestRetryanalyse" name="passWord" time="0.0">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.coach.TestRetryanalyse" name="passWord" time="0.001">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.coach.TestRetryanalyse" name="passWord" time="0.001">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.coach.TestRetryanalyse" name="passWord" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [12345] but found [54321]">
      <![CDATA[java.lang.AssertionError: expected [12345] but found [54321]
at com.testng.coach.TestRetryanalyse.passWord(TestRetryanalyse.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.coach.TestRetryanalyse" name="uName" time="0.001"/>
</testsuite> <!-- Test -->
